name: 💡 Feature Request
description: Request new or enhanced functionality
title: "💡 <title>"
labels: ["💡 feature request", "🚦 needs triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the functionality you are proposing.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your proposal related to a problem or functionality gap?
    description: |
      If so, provide a clear and concise description of the problem or gap.
      Examples:
        - I'm always frustrated when this product...
        - It would be great if this product did this...
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe your proposal
    description: A clear concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: Let us know about other solutions you've tried or researched.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Is there anything else you can add about the proposal?
      You might want to link to related issues here, if you haven't already.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
